feat: [LSPD-5734] ProxyClient now add recipientId in connection command headers
liveaction/ninio pull request #18
Opened 2024-12-17 09:46 UTC by eliep

When a sinemapro-slave send a connect command (to a proxy or a gateway), it now includes the recipientId in the command header.
This allow the collect-gateway to properly route the packet from the collect-agent to the sinemapro-slave.
This field is ignored by proxy

2025-01-14 10:02 UTC, baptistelebail requested changes

2025-01-14 10:02 UTC, baptistelebail commented on ninio-proxy/src/test/java/com/davfx/ninio/proxy/EchoTest.java
> +						try (Connecter client = ninio.create(proxyClient.factory("1").header(new ProxyHeader("_")).with(new Address(Address.LOCALHOST, port)))) {
Add a `const DEFAULT_RECIPIENT_ID` to avoid a magic string and make it clearer

2025-01-14 10:02 UTC, baptistelebail commented on ninio-proxy/src/test/java/com/davfx/ninio/proxy/EchoTest.java
> +					try (Connecter client = ninio.create(proxyClient.factory("1").header(new ProxyHeader("_")).with(new Address(Address.LOCALHOST, port)))) {
Add a `const DEFAULT_RECIPIENT_ID` to avoid a magic string and make it clearer

2025-01-14 10:02 UTC, baptistelebail commented on ninio-proxy/src/test/java/com/davfx/ninio/proxy/PingTest.java
>  						client.connect(new PingConnection() {
Add a `const DEFAULT_RECIPIENT_ID` to avoid a magic string and make it clearer

2025-01-14 10:02 UTC, baptistelebail commented on ninio-proxy/src/test/java/com/davfx/ninio/proxy/ProxyOpenCloseOpenPingTest.java
> +					try (PingConnecter client0 = PingTimeout.wrap(1d, ninio.create(PingClient.builder().with(proxyClient0.raw("1"))))) {
Add a `const DEFAULT_RECIPIENT_ID` to avoid a magic string and make it clearer

2025-01-14 10:02 UTC, baptistelebail commented on ninio-proxy/src/test/java/com/davfx/ninio/proxy/ProxyOpenCloseOpenPingTest.java
> +					try (PingConnecter client1 = PingTimeout.wrap(1d, ninio.create(PingClient.builder().with(proxyClient1.raw("1"))))) {
Add a `const DEFAULT_RECIPIENT_ID` to avoid a magic string and make it clearer

2025-01-14 10:02 UTC, baptistelebail commented on ninio-proxy/src/test/java/com/davfx/ninio/proxy/ProxyOpenLeaveOpenPingTest.java
> +					try (PingConnecter client0 = PingTimeout.wrap(1d, ninio.create(PingClient.builder().with(proxyClient0.raw("1"))))) {
Add a `const DEFAULT_RECIPIENT_ID` to avoid a magic string and make it clearer

2025-01-14 10:02 UTC, baptistelebail commented on ninio-proxy/src/test/java/com/davfx/ninio/proxy/ProxyOpenLeaveOpenPingTest.java
> +							try (PingConnecter client1 = PingTimeout.wrap(1d, ninio.create(PingClient.builder().with(proxyClient1.raw("1"))))) {
Add a `const DEFAULT_RECIPIENT_ID` to avoid a magic string and make it clearer

2025-01-14 10:04 UTC, jcubells requested changes

2025-01-14 10:04 UTC, jcubells commented on ninio-proxy/src/main/java/com/davfx/ninio/proxy/ProxyHeader.java
> +	public ProxyHeader addParameter(String name, String value) {
Convention point, addParameter sounds like it should be void and withParameter should return a modified object

2025-01-14 10:04 UTC, jcubells commented on ninio-proxy/src/test/java/com/davfx/ninio/proxy/EchoTest.java
> +					if (header.startsWith("_")) {
Why change this ?

2025-01-14 14:30 UTC, eliep commented on ninio-proxy/src/test/java/com/davfx/ninio/proxy/EchoTest.java
> +					if (header.startsWith("_")) {
The header now contains one more parameter (recipient id) and is not equals to "_" anymore.
However, it still start with "_".

2025-01-15 09:05 UTC, baptistelebail approved these changes

2025-01-15 09:20 UTC, jcubells approved these changes

2025-01-16 10:28 UTC, merged